### ISSUE TITLE
case studies in home page are displayed vertically

### ISSUE THREAD

**Issue by lucacioria** [buildo/buildo.io#245]
## description
per mockup, they should be side by side, but they are in 2 lines:
![image](https://user-images.githubusercontent.com/554092/35408741-80667d86-0210-11e8-9e91-23d18b9e0a94.png)

## specs
- make it responsive
  - 2 case studies per line? ask @alessandravilla

**Comment by alessandravilla** [comment]
on desktop and tablet they should be side by side
mockup: https://zpl.io/a8lnrZJ

**Comment by ecamellini** [comment]
@lucacioria @alessandravilla I'll fix it now. At the moment they are side by side only on desktop (luca your screen is probably tablet size, that's why you see them vertically 😛 )
