### ISSUE TITLE
Design pagina hiring (da nuova backbone)

### ISSUE THREAD

**Issue by ecamellini** [buildo/buildo.io#277]
[Project card](https://github.com/buildo/buildo.io/projects/1?fullscreen=true#card-17699014)

Wireframe: https://app.moqups.com/S794QUeE3G/edit/page/a614f8f41
Mockup: https://share.goabstract.com/877c1a3e-78b3-455c-91a6-f456f97db303
Intervista: https://paper.dropbox.com/doc/Intervista-hiring-page--AaHw4vrwRBFM1uhhmSlt4y8NAg-gYNdaTh9hCGx2LWdpOEAL

**Comment by alessandravilla** [comment]
To do:
- [ ] sezione posizione aperte
- [ ] foto aggiornate
- [ ] testi aggiornati
- [ ] immagini testo aggiornate
- [ ] versione mobile
