### ISSUE TITLE
User testing new hiring page {interview tunnata}

### ISSUE THREAD

**Issue by ecamellini** [buildo/buildo.io#280]
User testing new hiring page:

- how?
- who?

to be defined.
Paper https://paper.dropbox.com/doc/Intervista-hiring-page--Adi1eZhGznpqctTFSamCJQiHAg-gYNdaTh9hCGx2LWdpOEAL

**Comment by alessandravilla** [comment]
Rileggendo lo script mi sono resa conto che dopo il workshop lo avevamo già sistemato, rendendo tutte le domande aperte e creando le domande di followup. Per me ok possiamo chiudere il task @gabro @ecamellini
