### ISSUE TITLE
Inviare materiale a Studio Fond

### ISSUE THREAD

**Issue by ecamellini** [buildo/buildo.io#288]
https://paper.dropbox.com/doc/Log-buildo.io-website--AdPZnvnNN_vCYwGzd13ImQL1Ag-GUXAAtp00trVkUCh7uacs#:uid=737911283343768682987973&h2=Incontro-con-Studio-Fond

**Comment by raasoft** [comment]
Inviato brief ad @alessandravilla. Mi rimuovo quindi dal task.
