### ISSUE TITLE
Aggiornare mockups pagina hiring dopo interviste

### ISSUE THREAD

**Issue by alessandravilla** [buildo/buildo.io#289]
Action points:

- [ ] aggiungere come prima sezione (menzionare i processi, i tool, tecnologie moderne) [wireframe](https://app.moqups.com/S794QUeE3G/edit/page/a614f8f41)
- [ ] inserire contenuti che cosa farai tu a buildo (annuncio su meritocracy)
- [x] togliere la sezione professionality lasciando l’immagine nella sezione sotto
- [ ] cambiare foto “a place to learn…”

**Comment by alessandravilla** [comment]
@gabro potresti definire i contenuti della prima sezione (processi, tool, tecnologie moderne..) nei wireframe?
Per meritocracy  abbiamo già qualcosa di pronto? o posso vedere degli esempi per inserire qualcosa di simile nei mockup?

**Comment by alessandravilla** [comment]
@zanza00 ci servirebbe una foto per sostituire [questa](https://projects.invisionapp.com/d/main#/console/17199222/356530601/preview), la seconda nel mockup interattivo
qualcuno di noi che parta ad un meetup o conferenze, noi in cerchio che parliamo.. qualcosa che renda l'idea dell dimensioni dell'azienda e parli di community. Sai se abbiamo qualcosa? oppure riesci a farne una

**Comment by gabro** [comment]
Aggiornati i mockup. Non sono 100% convinto dei testi, ma le interview servono anche a questo :D

**Comment by alessandravilla** [comment]
> @zanza00 ci servirebbe una foto per sostituire [questa](https://projects.invisionapp.com/d/main#/console/17199222/356530601/preview) (la seconda nel mockup interattivo)
> qualcuno di noi che parta ad un meetup o conferenze, noi in cerchio che parliamo.. qualcosa che renda l'idea dell dimensioni dell'azienda e parli di community. Sai se abbiamo qualcosa? oppure riesci a farne una

@zanza00  hai poi fatto qualche foto?

**Comment by alessandravilla** [comment]
@gabro per il primo paragrafo come action points avevamo definito: "aggiungere come prima sezione (menzionare i processi, i tool, tecnologie moderne)", non vedo menzionate le tecnologie e i tools. Hai cambiato idea?
