### ISSUE TITLE
Presentazione nuove proposte e feedback a Studio Fond

### ISSUE THREAD

**Issue by ecamellini** [buildo/buildo.io#315]

**Comment by raasoft** [comment]
Mio feedback su ultima proposta Studio Fond:

# Proposta A1:

## CONTRO:
Il logo somiglia per certi aspetti ad un origami, lo ritengo eccessivamente "giocoso".

## PRO:
Confermo i pareri positivi espressi precedentemente, ovvero il font lo ritengo più al passo con i tempi, uso dei colori pieni e delle scritte sui muri molto azzeccate, e in generale tutti i pareri positivi espressi con la versione precedente connessi al concept della piega.

# Proposta A2 (versione logo evoluzione):

## PRO:
L' evoluzione del logo mi è piaciuta, è più compatibile con gli standard attuali di minimalismo ed è ottima per la creazione di una piccola animazione del logo che dal dettaglio del logo, zoomando, fa emergere il logo di buildo. Inoltre mi dà l' impressione di essere leggermente più seria, ma rimanendo "playful". 

## CONTRO:
Unico concern: il colore è diventato uno solo dei tre, mi piacerebbe vederli tutti e tre nel logo.
Mi sarebbe piaciuto capire la declinazione della nuova linea data dal logo nel resto della brand identity.


# Proposta C1 (versione logo standard):
## CONTRO:
Il logo tipografico non riesce a darmi un senso di appartenenza, lo sento come distante.
La versione con la 'b' singola potrebbe funzionare, ma la forma della costruzione mi risulta poco armoniosa e mi dà l' idea di "difficile da smussare", come se fossimo rigidi.
Non sono contento dei tre colori proposti) (nero, bianco e blu) che a mio avviso dovrebbero essere più morbidi per riflettere l'animo umano di buildo.

## PRO:
Apprezzo la scelta di colori non convenzionali che cerchino di differenziare la distintività dai competitor e l' animo innovativo.

Mi piacciono molto le pagine del sito, staccano molto bene i contenuti e il tono visivo è accattivante, mi spinge a leggere con interesse ciò che mi si presenta.

# Proposta C2:
Ragionamenti simili alla proposta C1, con leggera preferenza per la C1.
