### ISSUE TITLE
bottom-right chat causes some unwanted margin bottom

### ISSUE THREAD

**Issue by giogonzo** [buildo/buildo.io#80]
## description
<img width="1436" alt="screen shot 2017-06-01 at 11 48 24 am" src="https://cloud.githubusercontent.com/assets/2643520/26674324/646fe4ca-46c0-11e7-9522-dce41147273f.png">

## how to reproduce
- hard-refresh on chrome
- scroll down to the bottom of the page **fast**

refreshing with cached stuff OR refreshing and scrolling down only after the chat is fully rendered, there's no visual issue

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

**Comment by ecamellini** [comment]
Chat removed here: #126

**Comment by ecamellini** [comment]
Chat removed here: #126
