### ISSUE TITLE
page/background height is broken on Safari

### ISSUE THREAD

**Issue by giogonzo** [buildo/buildo.io#81]
## description

<img width="1437" alt="screen shot 2017-06-01 at 11 51 31 am" src="https://cloud.githubusercontent.com/assets/2643520/26674412/b2537b70-46c0-11e7-9afb-f6b7aab95026.png">

## how to reproduce
- scroll to the bottom on Safari
- scroll, scroll, scroll, scroll...

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

**Comment by ecamellini** [comment]
Not happening anymore.
