### ISSUE TITLE
serve properly sized images for WHO cards

### ISSUE THREAD

**Issue by giogonzo** [buildo/buildo.io#96]
## description
currently we are serving x3 images for cards (front and back) even if not strictly needed (e.g. non-retina or mobile screens)

the pixel size is 260. We are always serving `780px` images
(I'm not even sure why 260*2=520 is not enough?)

## how to reproduce
https://developers.google.com/speed/pagespeed/insights/?url=buildo.io

## specs
with a simple media query, we could save 350K on non-retinas and mobile devices

## misc
{optional: other useful info}

**Comment by ecamellini** [comment]
Images optimized here: #181
