### ISSUE TITLE
stars in /careers are too heavy

### ISSUE THREAD

**Issue by giogonzo** [buildo/buildo.io#97]
## description
find a way to put there something nice that doesn't kill computers, especially mobile phones

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
possible solutions:
- find a way to optimize the thing
- replace with a similar/lighter CSS animation
- remove animation completely, replace with a static image

## misc
{optional: other useful info}

**Comment by ecamellini** [comment]
Removed here: #204
